line_length:
  warning: 140
  error: 200
type_body_length:
  warning: 500
file_length:
  warning: 750

function_parameter_count:
  warning: 10
  error: 15

type_name:
  allowed_symbols: "_"

excluded:
  - .git
  - Pods
  - Carthage
  - "**/*Tests*"
  - "**/.build"
  - "**/DerivedData"
